update

diff --git a/.github/workflows/quality-checks.yml b/.github/workflows/quality-checks.yml
--- a/.github/workflows/quality-checks.yml
+++ b/.github/workflows/quality-checks.yml
@@ -20,7 +20,26 @@ jobs:
           workspace-notebook-path: /Workspace/Users/traininguser5@sudosu.ai/test_casestudy
           existing-cluster-id: ${{ secrets.DATABRICKS_CLUSTER_ID }}
 
-      - name: Download Deequ Report (if failed)
+      - name: Download and Print Deequ Report
+        if: always()
+        run: |
+          pip install databricks-cli jq
+          databricks configure --token <<EOF
+          ${{ secrets.DATABRICKS_HOST }}
+          ${{ secrets.DATABRICKS_TOKEN }}
+          EOF
+          databricks fs cp dbfs:/FileStore/shared_uploads/traininguser5@sudosu.ai/deequ_result.json ./deequ_result.json
+          echo "------ Deequ Output from Databricks ------"
+          cat deequ_result.json
+          echo "-------------------------------------------"
+          STATUS=$(jq -r '.result[0].check_status' deequ_result.json)
+          if [ "$STATUS" != "Success" ]; then
+            echo " Deequ checks failed"
+            exit 1
+          fi
+          echo " Deequ checks passed"
+
+      - name: Deequ Failure Message
         if: failure()
         run: |
           echo "Deequ failed — see DBFS report"
